config/routes.rb
# frozen_string_literal: true

# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#                     media POST   /media(.:format)                                                                         media#create
#               edit_medium GET    /media/:id/edit(.:format)                                                                media#edit
#                    medium GET    /media/:id(.:format)                                                                     media#show
#                           PATCH  /media/:id(.:format)                                                                     media#update
#                           PUT    /media/:id(.:format)                                                                     media#update
#                           DELETE /media/:id(.:format)                                                                     media#destroy
#              contributors GET    /contributors(.:format)                                                                  contributors#index
#                    genres GET    /genres(.:format)                                                                        genres#index
#                  category GET    /:category(.:format)                                                                     categories#index
#              new_category GET    /:category/new(.:format)                                                                 media#new
#                      root GET    /                                                                                        users#index
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  resources :media, except: %i[index new]
  resources :contributors, only: [:index]
  resources :genres, only: [:index]

  get ':category', controller: :categories, action: :index, as: :category
  get ':category/new', controller: :media, action: :new, as: :new_with_category

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/media_controller.rb
# frozen_string_literal: true

class MediaController < ApplicationController
  before_action :set_medium, only: %i[show edit update destroy]
  before_action :create_medium, only: %i[create]
  before_action :set_category, only: %i[new update]
  before_action :set_tags, only: %i[create update]
  before_action :validates_contributors, only: %i[create update]

  def index
    @media = Medium.eager_load(:genre,
                               :publisher,
                               :contributors,
                               :contributions)
                   .all
  end

  def show; end

  def edit; end

  def new
    @medium = Medium.new(category: @category)
    @medium.build_publisher
    @medium.contributors.build
  end

  def create
    respond_to do |format|
      if @medium.save
        format.html { redirect_to root_path, notice: 'medium was successfully created.' }
      #     format.json { render :new, status: :created, location: @medium }
      else
        format.html { render 'media/new' }
        #     format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # logger.debug @medium
    respond_to do |format|
      if @medium.update(medium_params.except(:contributors_attributes, :tag_list)) && @medium.save

        format.html { redirect_to root_path, notice: 'medium was successfully updated.' }
        format.json { render :edit, status: :ok, location: @medium }
      else
        format.html { render :edit }
        format.json { render json: @medium.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @medium.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'medium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_medium
    @medium = Medium.find(params[:id])
  end

  def medium_params
    params.require(:medium).permit(:title,
                                   :code,
                                   :category,
                                   :release,
                                   :genre_id,
                                   :description,
                                   :tag_list,
                                   publisher_attributes: %i[id name],
                                   contributors_attributes: %i[id name _destroy])
  end

  def create_medium
    @medium = Medium.new(medium_params.except(:contributors_attributes))
  end

  def validates_contributors
    new_contributors = []
    medium_params[:contributors_attributes].each do |_key, contributor|
      next if contributor[:_destroy] == '1' || contributor[:name].blank?

      new_contributors << Contributor
                          .where(name: contributor[:name].strip)
                          .first_or_create
    end
    @medium.contributors = new_contributors
  end

  def set_tags
    @medium.tag_list = medium_params[:tag_list].gsub(/[^a-zA-Z0-9]/,',')
  end

  def set_category
    return not_found unless !Medium.categories.include?(params[:category])

    @category = params[:category]
  end
end

app/views/media/_contributor_fields.html.haml
.col-6.nested-fields
  = f.input :name do
    .input-group.mb-3
      = f.input_field :name, class: 'form-control typeahead contributor', placeholder: 'Name of contributor'
      .input-group-append
        = link_to_remove_association "Remove Contributor", f, class: "btn btn-outline-danger"

app/views/media/_form.html.haml
= simple_form_for medium do |f|

  = f.error_notification

  .form-group
    .row
      .col
        = f.input :title, placeholder: 'Title of your medium'
      .col
        = f.input :category, collection: Medium.categories.keys.map { |c| [c.humanize, c]}
  .form-group
    .row
      .col
        = f.input :code, placeholder: 'ISBN, GTIN or barcode from your medium'
      .col
        = f.input :release, as: :string, placeholder: 'Date of release'
  .form-group
    .row
      .col
        = f.association :genre, collection: Genre.all.map { |g| [g.name, g.id]}, prompt: "Choose a genre"
      .col
        = f.input :description, placeholder: 'Description of your medium'

  .form-group
    .row
      .col
        = f.fields_for :publisher do |publisher|
          = render 'publisher_fields', f: publisher
      .col
        = f.input :cover
  .form-group
    .row
      .col
        = f.input :tag_list, label: 'Tags (seperated by comma)
'  #contributors.form-group
    %h3 Contributors
    .row
      .col.links
        = link_to_add_association 'Add Contributor', f, :contributors, class: "btn btn-outline-success", "data-association-insertion-node": ".row.contributors", "data-association-insertion-method": "append"
    .row.contributors
      = f.fields_for :contributors do |contributor|
        = render 'contributor_fields', f: contributor
  %hr
  .row
    .col.d-flex.justify-content-between
      = f.button :submit, class: "btn btn-primary"
      = f.button :button, "Reset", type: "reset", class: "btn-outline-secondary" unless medium.persisted?
      = link_to "Back", url_for(:back), class: "btn btn-secondary"

app/views/media/_medium.html.haml
%tr
  %td
    = medium.title
  %td
    = medium.genre.name
  %td
    = medium.code
  %td
    = medium.release
  %td
    - if medium.description.present?
      = medium.description.split(' ')[0..12].join(' ')+'..'
      = link_to "(more)", medium_path(medium)
  %td
    = medium.publisher.name
  %td
    = medium.contributors.pluck(:name).join(', ')
  %td
    = link_to medium_path(medium), class: 'btn btn-outline-dark' do
      = icon('fas', 'eye', 'Show')
  %td
    = link_to edit_medium_path(medium), class: 'btn btn-outline-secondary' do
      = icon('fas', 'edit', 'Edit')
  %td
    = link_to medium, method: :delete, data: {confirm: "Do you really want to delete #{medium.title}?"}, class: 'btn btn-outline-danger' do
      = icon('fas', 'trash', 'Remove')

app/views/media/_publisher_fields.html.haml
= f.input :name, label: 'Publisher' do
  = f.input_field :name, class: 'form-control typeahead contributor', placeholder: 'Name of publisher'

app/views/media/edit.html.haml
.container
  %h2 Edit Medium
  = render 'form', medium: @medium

app/views/media/index.html.haml
.container-fluid
  .row.justify-content-center
    .col-10
      %table.table
        %thead
          %tr
            %th Title
            %th Genre
            %th Serialcode
            %th Release
            %th Description
            %th Publisher
            %th Contributors
            %th{colspan: 3}
        %tbody
          = render @media
          %tr
            %td{colspan: 11}
              = link_to "New Medium", new_with_category_path, class: 'btn btn-outline-success'

app/views/media/new.html.haml
.container
  %h2 New Medium
  = render 'form', medium: @medium